version: '3'

services:
  react-client:
    build:
      context: ./client
    container_name: social-app_react-client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
    stdin_open: true
    depends_on:
      - api-server
    networks:
      - mern-app
  api-server:
    build:
      context: ./server
    container_name: social-app_api-server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/server
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.5-bionic
    container_name: mongo-db
    ports:
      - '27017:27017'
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data:/data/db
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
